import { Inter } from 'next/font/google'

import BasicTabs from '../../components/adminNavbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <BasicTabs />
      {children}</body>
    </html>
  )
}
